# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre y apellidos')),
                ('workplace', models.CharField(max_length=256, verbose_name='Lugar de trabajo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto de perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='T\xedtulo de la charla')),
                ('abstract', models.TextField(verbose_name='Resumen de la charla')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Tiempo estimado')),
                ('is_workshop', models.BooleanField(verbose_name='\xbfEs un taller?')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assistant', verbose_name='Asistente')),
            ],
        ),
    ]
