# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'verbose_name': 'Asistente'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'verbose_name': 'Charla'},
        ),
    ]
