# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160117_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto de perfil')),
                ('bio', models.CharField(max_length=512, verbose_name='Bio')),
                ('talk_title', models.CharField(max_length=128, verbose_name='T\xedtulo de la charla')),
                ('talk_abstract', models.TextField(verbose_name='Resumen de la charla')),
                ('talk_duration', models.PositiveSmallIntegerField(verbose_name='Tiempo estimado')),
                ('talk_is_workshop', models.BooleanField(verbose_name='\xbfEs un taller?')),
            ],
            options={
                'verbose_name': 'Asistente',
            },
        ),
        migrations.RemoveField(
            model_name='talk',
            name='assistant',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='avatar',
        ),
        migrations.AddField(
            model_name='assistant',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Talla S'), ('M', 'Talla M'), ('L', 'Talla L'), ('X', 'Talla X'), ('XL', 'Talla XL'), ('XXL', 'Talla XXL')], default='L', max_length=8, verbose_name='Talla de camisa'),
        ),
        migrations.DeleteModel(
            name='Talk',
        ),
        migrations.AddField(
            model_name='speaker',
            name='assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assistant', verbose_name='Asistente'),
        ),
    ]
