# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160117_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Talla S'), ('M', 'Talla M'), ('L', 'Talla L'), ('XL', 'Talla XL'), ('XXL', 'Talla XXL')], default='L', max_length=8, verbose_name='Talla de camisa'),
        ),
    ]
