# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160117_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='girl_shirt',
            field=models.BooleanField(default=False, verbose_name='Camisa de chica'),
            preserve_default=False,
        ),
    ]
