# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_assistant_girl_shirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=512)),
                ('field_type', models.CharField(choices=[('I', 'INTEGER'), ('F', 'FLOAT'), ('D', 'DATE'), ('B', 'BOOLEAN'), ('S', 'STRING')], max_length=8)),
            ],
        ),
    ]
