# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Pase especial',
                'verbose_name_plural': 'Pases especiales',
            },
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Configuraci\xf3n', 'verbose_name_plural': 'Configuraciones'},
        ),
    ]
