# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160409_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='field_type',
            field=models.CharField(choices=[('I', 'INTEGER'), ('F', 'FLOAT'), ('D', 'DATE'), ('B', 'BOOLEAN'), ('S', 'STRING')], max_length=8, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=256, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=512, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='code',
            field=models.CharField(max_length=16, verbose_name='C\xf3digo'),
        ),
    ]
